### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by colramos-amd** [portothree/mongo-to-grafana#18]
Hi, I'm **trying to build the project** and am using the [general build routine](https://grafana.com/tutorials/build-a-data-source-plugin/#create-a-new-plugin) for Grafana custom datasources/plugins:

1. `yarn install`
2. `yarn dev`

The `yarn install` works normally, but I run into this error when running `yarn dev`

```
$ yarn dev
yarn run v1.22.5
error Command "dev" not found.
```

I would appreciate it if someone could share some instruction on the proper way to run the project after cloning. Was unable to find this documentation in the `README.md`

**Comment by portothree** [comment]
Hello @colramos-amd,

Grafana 7+ changed a lot of the way plugins are built, my repo still uses https://grafana.com/docs/grafana/v6.0/plugins/developing/development/ as base for plugin development.

I'll try to update the README to be more helpful, but the steps are:
1. Run the server with `npm run server` or `node server/mongo-proxy.js`, its defaults to port `3333`.
2. Clone the project in `/usr/local/var/lib/grafana/plugins` folder
3. Build the plugin front end with `npm run build` or `npx gulp`
4. Make sure the `dist` folder was created
5. Restart the Grafana server. If installed via Homebrew, this can be done with `brew services restart grafana`

You should now see the "Mongo to Grafana" plugin in your grafana plugins page

**Comment by colramos-amd** [comment]
Thanks for sharing @portothree. Was also able to find these instructions [here](https://github.com/JamesOsgood/mongodb-grafana#install-and-start-the-mongodb-proxy-server) if anyone is curious.

Issue resolved.

**Comment by ycsin** [comment]
@portothree I'm running this on v8.1.5, works fine

**Comment by portothree** [comment]
> @portothree I'm running this on v8.1.5, works fine

Good to know! I have some 7+ instances as well. I guess they just changed the way to develop plugins, but kept the compatibility

**Comment by f0o** [comment]
@portothree I'm a bit lost how to get this to run.

What I've done:

1. Created a Dockerfile with contents:
  ```
  FROM node:lts-alpine
  ADD . /opt/app
  WORKDIR /opt/app
  RUN yarn install && npm run build
  CMD [ "npm", "run", "server" ]
  ```
2. Copied the folder `/opt/app/dist` out into `/var/lib/grafana/plugins/grafana-datasource-mongodb/dist`
1. Restarted Grafana's container (grafana-oss:latest) & verified that `/var/lib/grafana/plugins/grafana-datasource-mongodb/dist` exists and contains files.
1. Browsed to Settings -> Plugins
1. ???
1. Cant find your plugin...

Seems like I'm missing a step somewhere, any idea?
