### ISSUE TITLE
Internal server error when querying mongo

### ISSUE THREAD

**Issue by Parkietje** [portothree/mongo-to-grafana#29]
Hi! 

I'm getting a 500 error with message "Cannot read properties of null (reading '0')" .

I'm running Grafana 8.5.5 and mongo 5.0.4. 
Adding the data source worked just fine, the "/" query completed and I got the green infobox "MongoDB connection test OK"

I guess my query is wrong but no clue why. 
My query works fine when executed with mongoshell, but I'm getting an error running this query from Grafana:

db.test.aggregate([ 
 { $match : {  value : 'test'} }
])

Any help would be greatly appreciated!

**Comment by portothree** [comment]
Hey @Parkietje, good to hear that you found a solution.

I have seen problems with the `JSON.parse()` part before, like with this issue: https://github.com/portothree/grafana-datasource-mongodb/issues/22

I want to make this more resilient and give more useful errors and logs, like you suggested. PRs welcome :smile:
